version: "2"

services:
  nrdb-dev:
    container_name: nrdb-dev
    build: .
    depends_on:
      - nrdb-dev-db
    ports:
      - "8080:80"
    links:
      - nrdb-dev-db

  nrdb-dev-db:
    container_name: nrdb-dev-db
    image: "mysql:5"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: nrdb-dev
      MYSQL_USER: nrdb-dev
      MYSQL_PASSWORD: passwd

volumes:
  dbdata:
